// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {llm} from '../models';
import {main} from '../models';

export function CreateEntry(arg1:string,arg2:string,arg3:string):Promise<database.CodexEntry>;

export function CreateNewVault(arg1:string):Promise<string>;

export function DeleteEntry(arg1:number):Promise<void>;

export function FetchOpenRouterModelsWithKey(arg1:string):Promise<Array<llm.OpenRouterModel>>;

export function GenerateMissingEmbeddings():Promise<void>;

export function GenerateOpenRouterContent(arg1:string,arg2:string):Promise<string>;

export function GetAIResponseWithContext(arg1:string,arg2:string):Promise<string>;

export function GetAllEntries():Promise<Array<database.CodexEntry>>;

export function GetCurrentVaultPath():Promise<string>;

export function GetSettings():Promise<llm.OpenRouterConfig>;

export function ImportStoryTextAndFile(arg1:string):Promise<Array<database.CodexEntry>>;

export function ListChatLogs():Promise<Array<string>>;

export function ListLibraryFiles():Promise<Array<string>>;

export function LoadChatLog(arg1:string):Promise<Array<main.ChatMessage>>;

export function ProcessAndSaveTextAsEntries(arg1:string):Promise<number>;

export function ProcessStory(arg1:string):Promise<main.ProcessStoryResult>;

export function ReadLibraryFile(arg1:string):Promise<string>;

export function SaveAPIKeyOnly(arg1:string):Promise<void>;

export function SaveChatLog(arg1:string,arg2:Array<main.ChatMessage>):Promise<void>;

export function SaveLibraryFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:llm.OpenRouterConfig):Promise<void>;

export function SelectVaultFolder():Promise<string>;

export function SwitchVault(arg1:string):Promise<void>;

export function UpdateEntry(arg1:database.CodexEntry):Promise<void>;
