// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateEntry'](arg1, arg2, arg3);
}

export function CreateNewVault(arg1) {
  return window['go']['main']['App']['CreateNewVault'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GenerateContent(arg1) {
  return window['go']['main']['App']['GenerateContent'](arg1);
}

export function GetAllEntries() {
  return window['go']['main']['App']['GetAllEntries']();
}

export function GetCurrentVaultPath() {
  return window['go']['main']['App']['GetCurrentVaultPath']();
}

export function ImportStoryTextAndFile(arg1) {
  return window['go']['main']['App']['ImportStoryTextAndFile'](arg1);
}

export function ListLibraryFiles() {
  return window['go']['main']['App']['ListLibraryFiles']();
}

export function ProcessStory(arg1) {
  return window['go']['main']['App']['ProcessStory'](arg1);
}

export function ReadLibraryFile(arg1) {
  return window['go']['main']['App']['ReadLibraryFile'](arg1);
}

export function SelectVaultFolder() {
  return window['go']['main']['App']['SelectVaultFolder']();
}

export function SwitchVault(arg1) {
  return window['go']['main']['App']['SwitchVault'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}
