// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyDatabase(arg1:string):Promise<void>;

export function CreateEntry(arg1:string,arg2:string,arg3:string):Promise<main.CodexEntry>;

export function DeleteEntry(arg1:number):Promise<void>;

export function GenerateContent(arg1:string):Promise<string>;

export function GetAllEntries():Promise<Array<main.CodexEntry>>;

export function GetCurrentDatabasePath():Promise<string>;

export function GetEntryByID(arg1:number):Promise<main.CodexEntry>;

export function IsDatabaseLoaded():Promise<boolean>;

export function ProcessStory(arg1:string):Promise<Array<main.CodexEntry>>;

export function SaveDatabaseFile():Promise<string>;

export function SelectDatabaseFile():Promise<string>;

export function SwitchDatabase(arg1:string):Promise<void>;

export function UpdateEntry(arg1:main.CodexEntry):Promise<void>;
