// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateEntry'](arg1, arg2, arg3);
}

export function CreateNewVault(arg1) {
  return window['go']['main']['App']['CreateNewVault'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function FetchGeminiModels() {
  return window['go']['main']['App']['FetchGeminiModels']();
}

export function FetchOpenAIModels() {
  return window['go']['main']['App']['FetchOpenAIModels']();
}

export function FetchOpenRouterModelsWithKey(arg1) {
  return window['go']['main']['App']['FetchOpenRouterModelsWithKey'](arg1);
}

export function GenerateLLMContent(arg1, arg2) {
  return window['go']['main']['App']['GenerateLLMContent'](arg1, arg2);
}

export function GenerateMissingEmbeddings() {
  return window['go']['main']['App']['GenerateMissingEmbeddings']();
}

export function GenerateOpenRouterContent(arg1, arg2) {
  return window['go']['main']['App']['GenerateOpenRouterContent'](arg1, arg2);
}

export function GetAIResponseWithContext(arg1, arg2) {
  return window['go']['main']['App']['GetAIResponseWithContext'](arg1, arg2);
}

export function GetAllEntries() {
  return window['go']['main']['App']['GetAllEntries']();
}

export function GetCurrentVaultPath() {
  return window['go']['main']['App']['GetCurrentVaultPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportStoryTextAndFile(arg1, arg2) {
  return window['go']['main']['App']['ImportStoryTextAndFile'](arg1, arg2);
}

export function ListChatLogs() {
  return window['go']['main']['App']['ListChatLogs']();
}

export function ListLibraryFiles() {
  return window['go']['main']['App']['ListLibraryFiles']();
}

export function LoadChatLog(arg1) {
  return window['go']['main']['App']['LoadChatLog'](arg1);
}

export function MergeEntryContentDirect(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeEntryContentDirect'](arg1, arg2, arg3);
}

export function MergeEntryContentWithRAG(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeEntryContentWithRAG'](arg1, arg2, arg3);
}

export function ProcessAndSaveTextAsEntries(arg1) {
  return window['go']['main']['App']['ProcessAndSaveTextAsEntries'](arg1);
}

export function ProcessStory(arg1) {
  return window['go']['main']['App']['ProcessStory'](arg1);
}

export function ReadLibraryFile(arg1) {
  return window['go']['main']['App']['ReadLibraryFile'](arg1);
}

export function SaveAPIKeyOnly(arg1) {
  return window['go']['main']['App']['SaveAPIKeyOnly'](arg1);
}

export function SaveChatLog(arg1, arg2) {
  return window['go']['main']['App']['SaveChatLog'](arg1, arg2);
}

export function SaveLibraryFile(arg1, arg2) {
  return window['go']['main']['App']['SaveLibraryFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectVaultFolder() {
  return window['go']['main']['App']['SelectVaultFolder']();
}

export function SwitchVault(arg1) {
  return window['go']['main']['App']['SwitchVault'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}
