// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyDatabase(arg1) {
  return window['go']['main']['App']['CopyDatabase'](arg1);
}

export function CreateEntry(arg1) {
  return window['go']['main']['App']['CreateEntry'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GenerateContent(arg1) {
  return window['go']['main']['App']['GenerateContent'](arg1);
}

export function GetAllEntries() {
  return window['go']['main']['App']['GetAllEntries']();
}

export function GetCurrentDatabasePath() {
  return window['go']['main']['App']['GetCurrentDatabasePath']();
}

export function GetEntryByID(arg1) {
  return window['go']['main']['App']['GetEntryByID'](arg1);
}

export function IsDatabaseLoaded() {
  return window['go']['main']['App']['IsDatabaseLoaded']();
}

export function ProcessStory(arg1) {
  return window['go']['main']['App']['ProcessStory'](arg1);
}

export function SaveDatabaseFile() {
  return window['go']['main']['App']['SaveDatabaseFile']();
}

export function SelectDatabaseFile() {
  return window['go']['main']['App']['SelectDatabaseFile']();
}

export function SwitchDatabase(arg1) {
  return window['go']['main']['App']['SwitchDatabase'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}
