// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateEntry(arg1:string,arg2:string,arg3:string):Promise<main.CodexEntry>;

export function CreateNewVault(arg1:string):Promise<string>;

export function DeleteEntry(arg1:number):Promise<void>;

export function GenerateContent(arg1:string):Promise<string>;

export function GetAllEntries():Promise<Array<main.CodexEntry>>;

export function GetCurrentVaultPath():Promise<string>;

export function ImportStoryTextAndFile(arg1:string):Promise<Array<main.CodexEntry>>;

export function ListLibraryFiles():Promise<Array<string>>;

export function ProcessStory(arg1:string):Promise<Array<main.CodexEntry>>;

export function ReadLibraryFile(arg1:string):Promise<string>;

export function SelectVaultFolder():Promise<string>;

export function SwitchVault(arg1:string):Promise<void>;

export function UpdateEntry(arg1:main.CodexEntry):Promise<void>;
